name: tabungan
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.0.0
  shelf: ^1.1.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  shelf_router: ^1.0.0
  mysql1: ^0.20.0
  dart_jsonwebtoken: ^2.4.2
  crypto: ^3.0.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
